# 完善特征值特征向量计算PCA算法，使计算结果和使用sklearn中的库PCA计算结果完全一样

```
from sklearn.decomposition import PCA
from sklearn import datasets
# 加载数据
X,y = datasets.load_iris(return_X_y=1)

# 1、去中心化
B = X - X.mean(axis = 0)
B[:5]

# 2、协方差
# 方差是协方差特殊形式
# 协方差矩阵
V = np.cov(B,rowvar=False,bias = True)

# 3、协方差矩阵的特征值和特征向量
# 特征值和特征向量矩阵的概念
eigen,ev = np.linalg.eig(V)
display(eigen,ev)

# 4、降维标准，2个特征，选取两个最大的特征值所对应的特征的特征向量
#  百分比，计算各特征值，占权重，累加可以
cond = (eigen/eigen.sum()).cumsum() >= 0.98
index = cond.argmax()
ev = ev[:,:index + 1]

# 5、进行矩阵运算
pca_result = B.dot(ev)

# 6、标准化
pca_result = (pca_result -pca_result.mean(axis = 0))/pca_result.std(axis = 0,ddof = 1)
pca_result[:5]
```

直接使用sklearn中PCA得到结果：

```
array([[-1.30533786,  0.64836932, -0.09981716],
       [-1.31993521, -0.35930856, -0.75257299],
       [-1.40496732, -0.29424412,  0.0640073 ],
       [-1.33510889, -0.64613986,  0.11284924],
       [-1.32702321,  0.6633044 ,  0.32210314]])
```

自己计算（特征值特征向量法）结果：

```
array([[-1.30533786, -0.64836932, -0.09981716],
       [-1.31993521,  0.35930856, -0.75257299],
       [-1.40496732,  0.29424412,  0.0640073 ],
       [-1.33510889,  0.64613986,  0.11284924],
       [-1.32702321, -0.6633044 ,  0.32210314]])
```

对比可发现，第二列正负正好相反（注意，如果属性多，有多列，那么有可能其他列也存在这种情况奥~）

In [3]:
import numpy as np 
from sklearn import datasets

# 加载数据
X,y = datasets.load_iris(return_X_y=True)

# 1、去中心化
B = X - X.mean(axis = 0)
B[:5]

# 2、协方差
# 方差是协方差特殊形式
# 协方差矩阵
V = np.cov(B,rowvar=False,bias = True)

# 3、协方差矩阵的特征值和特征向量
# 特征值和特征向量矩阵的概念
eigen,ev = np.linalg.eig(V)
display(eigen,ev)

# 4、降维标准，2个特征，选取两个最大的特征值所对应的特征的特征向量
#  百分比，计算各特征值，占权重，累加可以
cond = (eigen/eigen.sum()).cumsum() >= 0.98
index = cond.argmax()
ev = ev[:,:index + 1]

# 5、进行矩阵运算
pca_result = B.dot(ev)

# 6、标准化
pca_result = (pca_result -pca_result.mean(axis = 0))/pca_result.std(axis = 0,ddof = 1)
pca_result[:5]

array([4.20005343, 0.24105294, 0.0776881 , 0.02367619])

array([[ 0.36138659, -0.65658877, -0.58202985,  0.31548719],
       [-0.08452251, -0.73016143,  0.59791083, -0.3197231 ],
       [ 0.85667061,  0.17337266,  0.07623608, -0.47983899],
       [ 0.3582892 ,  0.07548102,  0.54583143,  0.75365743]])

array([[-1.30533786, -0.64836932, -0.09981716],
       [-1.31993521,  0.35930856, -0.75257299],
       [-1.40496732,  0.29424412,  0.0640073 ],
       [-1.33510889,  0.64613986,  0.11284924],
       [-1.32702321, -0.6633044 ,  0.32210314]])